definitions:
  Error:
    type: "object"
    properties:
      error:
        type: string
        description: "Message, that describes what went wrong"
        example: "Error message"
  OKResponse:
    type: "object"
    properties:
      ok:
        type: boolean
        example: true
