
###
POST http://localhost:9005/api/v1/RefreshEbayVehicles

###
POST http://localhost:9005/api/v1/FindCompatibles
Content-Type: application/json

[
  {
    "make": "Yamaha",
    "year": 2014,
    "model": "WR 450 F"
  },
  {
    "make": "Yamaha",
    "year": 2012,
    "model": "WR 250 F"
  },
  {
    "make": "Yamaha",
    "year": 2010,
    "model": "WR 250 F"
  }
]

